site_name: Event-Driven Autoscaling with KEDA
site_description: Spring Boot workshop for Kafka-driven autoscaling with KEDA

nav:
  - Overview: index.md
  - KEDA: keda.md
  - Spring Boot: springboot.md
  - Links: links.md

plugins:
  - techdocs-core
